version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.rails-app
    container_name: web
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    volumes:
      - .:/rails_app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/bundle_cache
    env_file:
      - .env
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    command: >
      bash -c "bundle install 
      && bin/dev"
    depends_on:
      - db

  db:
    image: postgres:15.4
    container_name: db
    hostname: db
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  bundle_cache:
  postgres_data:
